services:
  mongodb:
    image: mongo:7
    container_name: notes_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: notesapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - notes_network

networks:
  notes_network:
    name: notes_network

volumes:
  mongodb_data:
    name: notes_mongodb_data
  mongodb_config:
    name: notes_mongodb_config
